In [6]:
import numpy as np

num1 = [1,2,3,4]
num2= [5,6,7,8]
print(num1 +num2)
# 데이터가 합쳐짐

# 넘파일로 리스트를 생성
x = np.array([1.,2,3,4])
print(x)
print(type(x))
print(x.shape) # 행, 열 > 4열

[1. 2. 3. 4.]
<class 'numpy.ndarray'>
(4,)


In [12]:
 # numpy 연산
x = np.array([1.0,2.0,3.0])
y = np.array([2.0,4.0,6.0])

# 1차원 리스트에서는 항목의 개수가 다를경우 오류 생성
print(x+y)
print(x-y)
print(x*y)
print(x/y)

[3. 6. 9.]
[-1. -2. -3.]
[ 2.  8. 18.]
[0.5 0.5 0.5]


In [1]:
# 한가지 자료형만 허용
import numpy as np
a = np.array([1,2,'a','b'])
print(a)
# 일반 리슽 - 여러가지 자료형 허용
cart = ['생수','감자',100,True]
cart

['1' '2' 'a' 'b']


['생수', '감자', 100, True]

In [34]:
# 넘파이 이차원 리스트
# 넘파이에서는 항목의 수가 같아야한다
# b = np.array([[1,2],[3]]) # > 오류
# print(b)
# print(b.shape)

c = np.array([[1,2],[3,4]]) # > 오류
print(c.dtype)
print(c.shape)
print(type(c))

int32
(2, 2)
<class 'numpy.ndarray'>


In [40]:
# zeros() - 리스트의 모든 인자를 0으로
# ones() - 리스트의 모든 인자를 1로

a1 = np.zeros((3,3))
print(a1)
print(a1.shape)
a2 = np.ones((2,3))
print(a2)



[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(3, 3)
[[1. 1. 1.]
 [1. 1. 1.]]


In [42]:
a3 = np.array((3,3))
print(a3)

[3 3]


In [4]:
# np.arange()
import numpy as np
print(range(10))
print(list(range(10)))
a= np.arange(10)
a3= np.arange(10) + 1
print(a3) # 외부요소를 리스트로
print(a) # 컴마가 없다
a2 = np.arange(3,9)
print(a2)

a4= np.arange(1,10,2)
print(a4)

range(0, 10)
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[ 1  2  3  4  5  6  7  8  9 10]
[0 1 2 3 4 5 6 7 8 9]
[3 4 5 6 7 8]
[1 3 5 7 9]
